# PBS configuration
queue: normalbw
project: x77
walltime: 48:00:00
jobname: ryf8_kds75
ncpus: 252
mem: 500GB

shortpath: /short/v45

runspersub: 7
restart_freq: 1

# Model configuration
model: access-om2
input: common_1deg_jra55
submodels:
    - name: atmosphere
      model: yatm
      exe: yatm_56fb5c87.exe
      input: yatm_1deg
      ncpus: 1

    - name: ocean
      model: mom
      exe: fms_ACCESS-OM_4135f906.x
      input:  
              - /g/data1/ua8/MOM/initial_conditions/WOA/10_KDS75
              - /g/data1/ua8/MOM/grids/10/topog/KDS75
              - /g/data/ua8/MOM/salinity_restoring/10
              - mom_1deg
      ncpus: 216

    - name: ice
      model: cice5
      exe: cice_auscom_360x300_24p_ab6ba104.exe
      input: cice_1deg
      ncpus: 24

platform:
    nodesize: 28

# Misc
runlog: True
stacksize: unlimited
collate_walltime: 1:00:00
collate_queue: express
collate_ncpus: 1
collate_mem: 8GB
collate_flags: -n4 -z -m -r
mpirun: --mca orte_base_help_aggregate 0
qsub_flags: -lother=hyperthread -W umask=027
# postscript: sync_output_to_gdata.sh
